Name: Otakings
IconPath: MyTeam.png
SoundPath: MyTeam.wav
Description: |
    Descriptions de Otakings
BrainsPackage: otakings
AgentsBrainClasses:
    WarBase: WarBaseBrainController
    WarExplorer: WarExplorerBrainController
    WarLight: WarLightBrainController
    WarHeavy: WarHeavyBrainController
    WarRocketLauncher: WarRocketLauncherBrainController
    WarKamikaze: WarKamikazeBrainController
    WarEngineer: WarEngineerBrainController
    WarTurret: WarTurretBrainController
